/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cwzeng' at '9/29/16 11:09 AM' with Gradle 2.14
 *
 * @author cwzeng, @date 9/29/16 11:09 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
